#!/usr/bin/env python3
"""
Imports the cleverden design-system icon set into AmityUIKit4 — ADDITIVELY.

- Copies every SVG from the cleverden icon source into its own imageset under
  Assets.xcassets/DesignSystemIcons/, configured as a TEMPLATE image with vector
  representation preserved (so it can be tinted by an Icon/* token at render).
- Generates AmityDesignSystemIcon.generated.swift: a nested `AmityIcon.DesignSystem`
  enum (String, ImageResourceProvider), camelCase cases, rawValue = exact Figma name.

Existing Assets.xcassets imagesets and the legacy `AmityIcon` cases are NOT touched —
those are shared with Social. New Figma names (`search-r`) don't collide with the SDK
imageset names, so this is purely additive.

Usage:
    python3 scripts/import_design_system_icons.py [CLEVERDEN_REPO_PATH]
    (default CLEVERDEN_REPO_PATH = /Users/zayar/Desktop/Amity/cleverden)
"""

import json
import os
import re
import shutil
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MODULE_DIR = os.path.join(SCRIPT_DIR, "..", "AmityUIKit4")
ASSET_GROUP = os.path.join(MODULE_DIR, "Assets.xcassets", "DesignSystemIcons")
OUTPUT_SWIFT = os.path.join(
    MODULE_DIR, "Core", "Utilities", "AmityDesignSystemIcon.generated.swift"
)

DEFAULT_CLEVERDEN = "/Users/zayar/Desktop/Amity/cleverden"


def camel_case(stem):
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", stem) if p]
    if not parts:
        raise SystemExit(f"error: cannot derive a case name from '{stem}'")
    name = parts[0][0].lower() + parts[0][1:] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    if name[0].isdigit():
        name = "_" + name
    return name


def main():
    cleverden = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_CLEVERDEN
    src_dir = os.path.join(cleverden, "uikit", "assets", "icons")
    if not os.path.isdir(src_dir):
        raise SystemExit(f"error: icon source not found: {src_dir}")

    svgs = sorted(f for f in os.listdir(src_dir) if f.endswith(".svg"))
    if not svgs:
        raise SystemExit(f"error: no SVGs in {src_dir}")

    # Fresh import: wipe and recreate the additive group only (never touches siblings).
    if os.path.isdir(ASSET_GROUP):
        shutil.rmtree(ASSET_GROUP)
    os.makedirs(ASSET_GROUP)
    # Folder Contents.json WITHOUT provides-namespace -> asset name stays the bare Figma name.
    with open(os.path.join(ASSET_GROUP, "Contents.json"), "w") as f:
        json.dump({"info": {"author": "xcode", "version": 1}}, f, indent=2)

    cases = {}  # caseName -> figmaName
    for svg in svgs:
        stem = os.path.splitext(svg)[0]
        case = camel_case(stem)
        if case in cases:
            raise SystemExit(f"error: case collision '{case}' ({cases[case]} vs {stem})")
        cases[case] = stem

        imageset = os.path.join(ASSET_GROUP, f"{stem}.imageset")
        os.makedirs(imageset)
        shutil.copyfile(os.path.join(src_dir, svg), os.path.join(imageset, svg))
        contents = {
            "images": [{"filename": svg, "idiom": "universal"}],
            "info": {"author": "xcode", "version": 1},
            "properties": {
                "preserves-vector-representation": True,
                "template-rendering-intent": "template",
            },
        }
        with open(os.path.join(imageset, "Contents.json"), "w") as f:
            json.dump(contents, f, indent=2)

    # Generate the Swift enum.
    lines = [
        "//",
        "//  AmityDesignSystemIcon.generated.swift",
        "//  AmityUIKit4",
        "//",
        "//  Auto-generated by scripts/import_design_system_icons.py from the cleverden",
        "//  UIKit icon set (uikit/assets/icons). Do not edit manually.",
        "//",
        "//  These are the new colour-agnostic design-system icons. They ship as template",
        "//  images and are meant to be tinted via an Icon/* token, e.g.:",
        "//",
        "//      Image(AmityIcon.DesignSystem.searchR.imageResource)",
        "//          .renderingMode(.template)",
        "//          .foregroundColor(Color(viewConfig.color(.iconGeneralDefault)))",
        "//",
        "",
        "import UIKit",
        "",
        "extension AmityIcon {",
        "    /// Design-system icons imported from Figma (colour-agnostic, token-tinted).",
        "    /// Additive — legacy `AmityIcon` cases (shared with Social) are untouched.",
        "    enum DesignSystem: String, ImageResourceProvider {",
    ]
    for case in sorted(cases):
        lines.append(f'        case {case} = "{cases[case]}"')
    lines.append("    }")
    lines.append("}")

    with open(OUTPUT_SWIFT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Imported {len(svgs)} icons -> {os.path.relpath(ASSET_GROUP, os.path.join(SCRIPT_DIR, '..'))}")
    print(f"Generated enum ({len(cases)} cases) -> {os.path.relpath(OUTPUT_SWIFT, os.path.join(SCRIPT_DIR, '..'))}")


if __name__ == "__main__":
    main()
