// Generated by `apollo features sync` from apollo/features.json. Do not edit.

import Foundation

/// UIKit modules a customer can switch off in config.json.
/// Naming the keys here rather than passing strings means a typo is a
/// compile error instead of a module that silently stays on — the failure
/// mode a flag exists to prevent.
public enum AmityUIKitFeature: String, CaseIterable {
    case community = "community"
    case chat = "chat"
    case live = "live"
    case poll = "poll"
    case userRelationship = "userRelationship"
    case pushNotification = "pushNotification"
    case post = "post"
    case story = "story"
    case events = "events"
    case feed = "feed"
    case comment = "comment"
    case reaction = "reaction"
    case product = "product"
    case ads = "ads"
    case discovery = "discovery"
}
